name: Daily Tasks

on:
  push:
  schedule:
    - cron: '0 * * * *'

jobs:
  check-in:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 5

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install
        run: yarn

      - name: Check In
        run: npm run serve
        env:
          DINGTALK_WEBHOOK: ${{ secrets.DINGTALK_WEBHOOK }}
          DINGTALK_SECRET: ${{ secrets.DINGTALK_SECRET }}
          ACFUN_COOKIE: ${{ secrets.ACFUN_COOKIE }}
          BILIBILI_COOKIE: ${{ secrets.BILIBILI_COOKIE }}
          MUSIC163_COOKIE: ${{ secrets.MUSIC163_COOKIE }}
          V2EX_COOKIE: ${{ secrets.V2EX_COOKIE }}
          DOUYU_COOKIE: ${{ secrets.DOUYU_COOKIE }}
          EGAME_COOKIE: ${{ secrets.EGAME_COOKIE}}
